package net.js.jsmenu.damage;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.damagesource.DamageSource;
import net.minecraft.world.damagesource.DamageType;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.level.Level;
import net.minecraft.world.phys.Vec3;

public class RadioactiveDamageTypes {
    public static final ResourceKey<DamageType> TECHNETIUM_ORE_STEP = createKey("technetium_ore_step");
    public static final ResourceKey<DamageType> TECHNETIUM_ORE_MINING = createKey("technetium_ore_mining");
    public static final ResourceKey<DamageType> TECHNETIUM_ORE_KARMA = createKey("technetium_ore_karma");
    public static final ResourceKey<DamageType> PROMETHIUM_ORE_STEP = createKey("promethium_ore_step");
    public static final ResourceKey<DamageType> PROMETHIUM_ORE_MINING = createKey("promethium_ore_mining");
    public static final ResourceKey<DamageType> PROMETHIUM_ORE_KARMA = createKey("promethium_ore_karma");
    public static final ResourceKey<DamageType> POLONIUM_ORE_STEP = createKey("polonium_ore_step");
    public static final ResourceKey<DamageType> POLONIUM_ORE_MINING = createKey("polonium_ore_mining");
    public static final ResourceKey<DamageType> POLONIUM_ORE_KARMA = createKey("polonium_ore_karma");
    public static final ResourceKey<DamageType> ASTATINE_ORE_STEP = createKey("astatine_ore_step");
    public static final ResourceKey<DamageType> ASTATINE_ORE_MINING = createKey("astatine_ore_mining");
    public static final ResourceKey<DamageType> ASTATINE_ORE_KARMA = createKey("astatine_ore_karma");
    public static final ResourceKey<DamageType> RADON_ORE_STEP = createKey("radon_ore_step");
    public static final ResourceKey<DamageType> RADON_ORE_MINING = createKey("radon_ore_mining");
    public static final ResourceKey<DamageType> RADON_ORE_KARMA = createKey("radon_ore_karma");
    public static final ResourceKey<DamageType> FRANCIUM_ORE_STEP = createKey("francium_ore_step");
    public static final ResourceKey<DamageType> FRANCIUM_ORE_MINING = createKey("francium_ore_mining");
    public static final ResourceKey<DamageType> FRANCIUM_ORE_KARMA = createKey("francium_ore_karma");
    public static final ResourceKey<DamageType> RADIUM_ORE_STEP = createKey("radium_ore_step");
    public static final ResourceKey<DamageType> RADIUM_ORE_MINING = createKey("radium_ore_mining");
    public static final ResourceKey<DamageType> RADIUM_ORE_KARMA = createKey("radium_ore_karma");
    public static final ResourceKey<DamageType> ACTINIUM_ORE_STEP = createKey("actinium_ore_step");
    public static final ResourceKey<DamageType> ACTINIUM_ORE_MINING = createKey("actinium_ore_mining");
    public static final ResourceKey<DamageType> ACTINIUM_ORE_KARMA = createKey("actinium_ore_karma");
    public static final ResourceKey<DamageType> THORIUM_ORE_STEP = createKey("thorium_ore_step");
    public static final ResourceKey<DamageType> THORIUM_ORE_MINING = createKey("thorium_ore_mining");
    public static final ResourceKey<DamageType> THORIUM_ORE_KARMA = createKey("thorium_ore_karma");
    public static final ResourceKey<DamageType> PROTACTINIUM_ORE_STEP = createKey("protactinium_ore_step");
    public static final ResourceKey<DamageType> PROTACTINIUM_ORE_MINING = createKey("protactinium_ore_mining");
    public static final ResourceKey<DamageType> PROTACTINIUM_ORE_KARMA = createKey("protactinium_ore_karma");
    public static final ResourceKey<DamageType> URANIUM_ORE_STEP = createKey("uranium_ore_step");
    public static final ResourceKey<DamageType> URANIUM_ORE_MINING = createKey("uranium_ore_mining");
    public static final ResourceKey<DamageType> URANIUM_ORE_KARMA = createKey("uranium_ore_karma");
    public static final ResourceKey<DamageType> NEPTUNIUM_ORE_STEP = createKey("neptunium_ore_step");
    public static final ResourceKey<DamageType> NEPTUNIUM_ORE_MINING = createKey("neptunium_ore_mining");
    public static final ResourceKey<DamageType> NEPTUNIUM_ORE_KARMA = createKey("neptunium_ore_karma");
    public static final ResourceKey<DamageType> PLUTONIUM_ORE_STEP = createKey("plutonium_ore_step");
    public static final ResourceKey<DamageType> PLUTONIUM_ORE_MINING = createKey("plutonium_ore_mining");
    public static final ResourceKey<DamageType> PLUTONIUM_ORE_KARMA = createKey("plutonium_ore_karma");
    public static final ResourceKey<DamageType> AMERICIUM_ORE_STEP = createKey("americium_ore_step");
    public static final ResourceKey<DamageType> AMERICIUM_ORE_MINING = createKey("americium_ore_mining");
    public static final ResourceKey<DamageType> AMERICIUM_ORE_KARMA = createKey("americium_ore_karma");
    public static final ResourceKey<DamageType> CURIUM_ORE_STEP = createKey("curium_ore_step");
    public static final ResourceKey<DamageType> CURIUM_ORE_MINING = createKey("curium_ore_mining");
    public static final ResourceKey<DamageType> CURIUM_ORE_KARMA = createKey("curium_ore_karma");
    public static final ResourceKey<DamageType> BERKELIUM_ORE_STEP = createKey("berkelium_ore_step");
    public static final ResourceKey<DamageType> BERKELIUM_ORE_MINING = createKey("berkelium_ore_mining");
    public static final ResourceKey<DamageType> BERKELIUM_ORE_KARMA = createKey("berkelium_ore_karma");
    public static final ResourceKey<DamageType> CALIFORNIUM_ORE_STEP = createKey("californium_ore_step");
    public static final ResourceKey<DamageType> CALIFORNIUM_ORE_MINING = createKey("californium_ore_mining");
    public static final ResourceKey<DamageType> CALIFORNIUM_ORE_KARMA = createKey("californium_ore_karma");
    public static final ResourceKey<DamageType> EINSTEINIUM_ORE_STEP = createKey("einsteinium_ore_step");
    public static final ResourceKey<DamageType> EINSTEINIUM_ORE_MINING = createKey("einsteinium_ore_mining");
    public static final ResourceKey<DamageType> EINSTEINIUM_ORE_KARMA = createKey("einsteinium_ore_karma");
    public static final ResourceKey<DamageType> FERMIUM_ORE_STEP = createKey("fermium_ore_step");
    public static final ResourceKey<DamageType> FERMIUM_ORE_MINING = createKey("fermium_ore_mining");
    public static final ResourceKey<DamageType> FERMIUM_ORE_KARMA = createKey("fermium_ore_karma");
    public static final ResourceKey<DamageType> MENDELEVIUM_ORE_STEP = createKey("mendelevium_ore_step");
    public static final ResourceKey<DamageType> MENDELEVIUM_ORE_MINING = createKey("mendelevium_ore_mining");
    public static final ResourceKey<DamageType> MENDELEVIUM_ORE_KARMA = createKey("mendelevium_ore_karma");
    public static final ResourceKey<DamageType> NOBELIUM_ORE_STEP = createKey("nobelium_ore_step");
    public static final ResourceKey<DamageType> NOBELIUM_ORE_MINING = createKey("nobelium_ore_mining");
    public static final ResourceKey<DamageType> NOBELIUM_ORE_KARMA = createKey("nobelium_ore_karma");
    public static final ResourceKey<DamageType> LAWRENCIUM_ORE_STEP = createKey("lawrencium_ore_step");
    public static final ResourceKey<DamageType> LAWRENCIUM_ORE_MINING = createKey("lawrencium_ore_mining");
    public static final ResourceKey<DamageType> LAWRENCIUM_ORE_KARMA = createKey("lawrencium_ore_karma");
    public static final ResourceKey<DamageType> RUTHERFORDIUM_ORE_STEP = createKey("rutherfordium_ore_step");
    public static final ResourceKey<DamageType> RUTHERFORDIUM_ORE_MINING = createKey("rutherfordium_ore_mining");
    public static final ResourceKey<DamageType> RUTHERFORDIUM_ORE_KARMA = createKey("rutherfordium_ore_karma");
    public static final ResourceKey<DamageType> DUBNIUM_ORE_STEP = createKey("dubnium_ore_step");
    public static final ResourceKey<DamageType> DUBNIUM_ORE_MINING = createKey("dubnium_ore_mining");
    public static final ResourceKey<DamageType> DUBNIUM_ORE_KARMA = createKey("dubnium_ore_karma");
    public static final ResourceKey<DamageType> SEABORGIUM_ORE_STEP = createKey("seaborgium_ore_step");
    public static final ResourceKey<DamageType> SEABORGIUM_ORE_MINING = createKey("seaborgium_ore_mining");
    public static final ResourceKey<DamageType> SEABORGIUM_ORE_KARMA = createKey("seaborgium_ore_karma");
    public static final ResourceKey<DamageType> BOHRIUM_ORE_STEP = createKey("bohrium_ore_step");
    public static final ResourceKey<DamageType> BOHRIUM_ORE_MINING = createKey("bohrium_ore_mining");
    public static final ResourceKey<DamageType> BOHRIUM_ORE_KARMA = createKey("bohrium_ore_karma");
    public static final ResourceKey<DamageType> HASSIUM_ORE_STEP = createKey("hassium_ore_step");
    public static final ResourceKey<DamageType> HASSIUM_ORE_MINING = createKey("hassium_ore_mining");
    public static final ResourceKey<DamageType> HASSIUM_ORE_KARMA = createKey("hassium_ore_karma");
    public static final ResourceKey<DamageType> MEITNERIUM_ORE_STEP = createKey("meitnerium_ore_step");
    public static final ResourceKey<DamageType> MEITNERIUM_ORE_MINING = createKey("meitnerium_ore_mining");
    public static final ResourceKey<DamageType> MEITNERIUM_ORE_KARMA = createKey("meitnerium_ore_karma");
    public static final ResourceKey<DamageType> DARMSTADTIUM_ORE_STEP = createKey("darmstadtium_ore_step");
    public static final ResourceKey<DamageType> DARMSTADTIUM_ORE_MINING = createKey("darmstadtium_ore_mining");
    public static final ResourceKey<DamageType> DARMSTADTIUM_ORE_KARMA = createKey("darmstadtium_ore_karma");
    public static final ResourceKey<DamageType> ROENTGENIUM_ORE_STEP = createKey("roentgenium_ore_step");
    public static final ResourceKey<DamageType> ROENTGENIUM_ORE_MINING = createKey("roentgenium_ore_mining");
    public static final ResourceKey<DamageType> ROENTGENIUM_ORE_KARMA = createKey("roentgenium_ore_karma");
    public static final ResourceKey<DamageType> COPERNICIUM_ORE_STEP = createKey("copernicium_ore_step");
    public static final ResourceKey<DamageType> COPERNICIUM_ORE_MINING = createKey("copernicium_ore_mining");
    public static final ResourceKey<DamageType> COPERNICIUM_ORE_KARMA = createKey("copernicium_ore_karma");
    public static final ResourceKey<DamageType> NIHONIUM_ORE_STEP = createKey("nihonium_ore_step");
    public static final ResourceKey<DamageType> NIHONIUM_ORE_MINING = createKey("nihonium_ore_mining");
    public static final ResourceKey<DamageType> NIHONIUM_ORE_KARMA = createKey("nihonium_ore_karma");
    public static final ResourceKey<DamageType> FLEROVIUM_ORE_STEP = createKey("flerovium_ore_step");
    public static final ResourceKey<DamageType> FLEROVIUM_ORE_MINING = createKey("flerovium_ore_mining");
    public static final ResourceKey<DamageType> FLEROVIUM_ORE_KARMA = createKey("flerovium_ore_karma");
    public static final ResourceKey<DamageType> MOSCOVIUM_ORE_STEP = createKey("moscovium_ore_step");
    public static final ResourceKey<DamageType> MOSCOVIUM_ORE_MINING = createKey("moscovium_ore_mining");
    public static final ResourceKey<DamageType> MOSCOVIUM_ORE_KARMA = createKey("moscovium_ore_karma");
    public static final ResourceKey<DamageType> LIVERMORIUM_ORE_STEP = createKey("livermorium_ore_step");
    public static final ResourceKey<DamageType> LIVERMORIUM_ORE_MINING = createKey("livermorium_ore_mining");
    public static final ResourceKey<DamageType> LIVERMORIUM_ORE_KARMA = createKey("livermorium_ore_karma");
    public static final ResourceKey<DamageType> TENNESSINE_ORE_STEP = createKey("tennessine_ore_step");
    public static final ResourceKey<DamageType> TENNESSINE_ORE_MINING = createKey("tennessine_ore_mining");
    public static final ResourceKey<DamageType> TENNESSINE_ORE_KARMA = createKey("tennessine_ore_karma");
    public static final ResourceKey<DamageType> OGANESSON_ORE_STEP = createKey("oganesson_ore_step");
    public static final ResourceKey<DamageType> OGANESSON_ORE_MINING = createKey("oganesson_ore_mining");
    public static final ResourceKey<DamageType> OGANESSON_ORE_KARMA = createKey("oganesson_ore_karma");
    public static final ResourceKey<DamageType> TECHNETIUM_BLOCK_STEP = createKey("technetium_block_step");
    public static final ResourceKey<DamageType> TECHNETIUM_BLOCK_MINING = createKey("technetium_block_mining");
    public static final ResourceKey<DamageType> TECHNETIUM_BLOCK_KARMA = createKey("technetium_block_karma");
    public static final ResourceKey<DamageType> PROMETHIUM_BLOCK_STEP = createKey("promethium_block_step");
    public static final ResourceKey<DamageType> PROMETHIUM_BLOCK_MINING = createKey("promethium_block_mining");
    public static final ResourceKey<DamageType> PROMETHIUM_BLOCK_KARMA = createKey("promethium_block_karma");
    public static final ResourceKey<DamageType> POLONIUM_BLOCK_STEP = createKey("polonium_block_step");
    public static final ResourceKey<DamageType> POLONIUM_BLOCK_MINING = createKey("polonium_block_mining");
    public static final ResourceKey<DamageType> POLONIUM_BLOCK_KARMA = createKey("polonium_block_karma");
    public static final ResourceKey<DamageType> ASTATINE_BLOCK_STEP = createKey("astatine_block_step");
    public static final ResourceKey<DamageType> ASTATINE_BLOCK_MINING = createKey("astatine_block_mining");
    public static final ResourceKey<DamageType> ASTATINE_BLOCK_KARMA = createKey("astatine_block_karma");
    public static final ResourceKey<DamageType> RADON_BLOCK_STEP = createKey("radon_block_step");
    public static final ResourceKey<DamageType> RADON_BLOCK_MINING = createKey("radon_block_mining");
    public static final ResourceKey<DamageType> RADON_BLOCK_KARMA = createKey("radon_block_karma");
    public static final ResourceKey<DamageType> FRANCIUM_BLOCK_STEP = createKey("francium_block_step");
    public static final ResourceKey<DamageType> FRANCIUM_BLOCK_MINING = createKey("francium_block_mining");
    public static final ResourceKey<DamageType> FRANCIUM_BLOCK_KARMA = createKey("francium_block_karma");
    public static final ResourceKey<DamageType> RADIUM_BLOCK_STEP = createKey("radium_block_step");
    public static final ResourceKey<DamageType> RADIUM_BLOCK_MINING = createKey("radium_block_mining");
    public static final ResourceKey<DamageType> RADIUM_BLOCK_KARMA = createKey("radium_block_karma");
    public static final ResourceKey<DamageType> ACTINIUM_BLOCK_STEP = createKey("actinium_block_step");
    public static final ResourceKey<DamageType> ACTINIUM_BLOCK_MINING = createKey("actinium_block_mining");
    public static final ResourceKey<DamageType> ACTINIUM_BLOCK_KARMA = createKey("actinium_block_karma");
    public static final ResourceKey<DamageType> THORIUM_BLOCK_STEP = createKey("thorium_block_step");
    public static final ResourceKey<DamageType> THORIUM_BLOCK_MINING = createKey("thorium_block_mining");
    public static final ResourceKey<DamageType> THORIUM_BLOCK_KARMA = createKey("thorium_block_karma");
    public static final ResourceKey<DamageType> PROTACTINIUM_BLOCK_STEP = createKey("protactinium_block_step");
    public static final ResourceKey<DamageType> PROTACTINIUM_BLOCK_MINING = createKey("protactinium_block_mining");
    public static final ResourceKey<DamageType> PROTACTINIUM_BLOCK_KARMA = createKey("protactinium_block_karma");
    public static final ResourceKey<DamageType> URANIUM_BLOCK_STEP = createKey("uranium_block_step");
    public static final ResourceKey<DamageType> URANIUM_BLOCK_MINING = createKey("uranium_block_mining");
    public static final ResourceKey<DamageType> URANIUM_BLOCK_KARMA = createKey("uranium_block_karma");
    public static final ResourceKey<DamageType> NEPTUNIUM_BLOCK_STEP = createKey("neptunium_block_step");
    public static final ResourceKey<DamageType> NEPTUNIUM_BLOCK_MINING = createKey("neptunium_block_mining");
    public static final ResourceKey<DamageType> NEPTUNIUM_BLOCK_KARMA = createKey("neptunium_block_karma");
    public static final ResourceKey<DamageType> PLUTONIUM_BLOCK_STEP = createKey("plutonium_block_step");
    public static final ResourceKey<DamageType> PLUTONIUM_BLOCK_MINING = createKey("plutonium_block_mining");
    public static final ResourceKey<DamageType> PLUTONIUM_BLOCK_KARMA = createKey("plutonium_block_karma");
    public static final ResourceKey<DamageType> AMERICIUM_BLOCK_STEP = createKey("americium_block_step");
    public static final ResourceKey<DamageType> AMERICIUM_BLOCK_MINING = createKey("americium_block_mining");
    public static final ResourceKey<DamageType> AMERICIUM_BLOCK_KARMA = createKey("americium_block_karma");
    public static final ResourceKey<DamageType> CURIUM_BLOCK_STEP = createKey("curium_block_step");
    public static final ResourceKey<DamageType> CURIUM_BLOCK_MINING = createKey("curium_block_mining");
    public static final ResourceKey<DamageType> CURIUM_BLOCK_KARMA = createKey("curium_block_karma");
    public static final ResourceKey<DamageType> BERKELIUM_BLOCK_STEP = createKey("berkelium_block_step");
    public static final ResourceKey<DamageType> BERKELIUM_BLOCK_MINING = createKey("berkelium_block_mining");
    public static final ResourceKey<DamageType> BERKELIUM_BLOCK_KARMA = createKey("berkekium_block_karma");
    public static final ResourceKey<DamageType> CALIFORNIUM_BLOCK_STEP = createKey("californium_block_step");
    public static final ResourceKey<DamageType> CALIFORNIUM_BLOCK_MINING = createKey("californium_block_mining");
    public static final ResourceKey<DamageType> CALIFORNIUM_BLOCK_KARMA = createKey("californium_block_karma");
    public static final ResourceKey<DamageType> EINSTEINIUM_BLOCK_STEP = createKey("einsteinium_block_step");
    public static final ResourceKey<DamageType> EINSTEINIUM_BLOCK_MINING = createKey("einsteinium_block_mining");
    public static final ResourceKey<DamageType> EINSTEINIUM_BLOCK_KARMA = createKey("einsteinium_block_karma");
    public static final ResourceKey<DamageType> FERMIUM_BLOCK_STEP = createKey("fermium_block_step");
    public static final ResourceKey<DamageType> FERMIUM_BLOCK_MINING = createKey("fermium_block_mining");
    public static final ResourceKey<DamageType> FERMIUM_BLOCK_KARMA = createKey("fermium_block_karma");
    public static final ResourceKey<DamageType> MENDELEVIUM_BLOCK_STEP = createKey("mendelevium_block_step");
    public static final ResourceKey<DamageType> MENDELEVIUM_BLOCK_MINING = createKey("mendelevium_block_mining");
    public static final ResourceKey<DamageType> MENDELEVIUM_BLOCK_KARMA = createKey("mendelevium_block_karma");
    public static final ResourceKey<DamageType> NOBELIUM_BLOCK_STEP = createKey("nobelium_block_step");
    public static final ResourceKey<DamageType> NOBELIUM_BLOCK_MINING = createKey("nobelium_block_mining");
    public static final ResourceKey<DamageType> NOBELIUM_BLOCK_KARMA = createKey("nobelium_block_karma");
    public static final ResourceKey<DamageType> LAWRENCIUM_BLOCK_STEP = createKey("lawrencium_block_step");
    public static final ResourceKey<DamageType> LAWRENCIUM_BLOCK_MINING = createKey("lawrencium_block_mining");
    public static final ResourceKey<DamageType> LAWRENCIUM_BLOCK_KARMA = createKey("lawrencium_block_karma");
    public static final ResourceKey<DamageType> RUTHERFORDIUM_BLOCK_STEP = createKey("rutherfordium_block_step");
    public static final ResourceKey<DamageType> RUTHERFORDIUM_BLOCK_MINING = createKey("rutherfordium_block_mining");
    public static final ResourceKey<DamageType> RUTHERFORDIUM_BLOCK_KARMA = createKey("rutherfordium_block_karma");
    public static final ResourceKey<DamageType> DUBNIUM_BLOCK_STEP = createKey("dubnium_block_step");
    public static final ResourceKey<DamageType> DUBNIUM_BLOCK_MINING = createKey("dubnium_block_mining");
    public static final ResourceKey<DamageType> DUBNIUM_BLOCK_KARMA = createKey("dubnium_block_karma");
    public static final ResourceKey<DamageType> SEABORGIUM_BLOCK_STEP = createKey("seaborgium_block_step");
    public static final ResourceKey<DamageType> SEABORGIUM_BLOCK_MINING = createKey("seaborgium_block_mining");
    public static final ResourceKey<DamageType> SEABORGIUM_BLOCK_KARMA = createKey("seaborgium_block_karma");
    public static final ResourceKey<DamageType> BOHRIUM_BLOCK_STEP = createKey("bohrium_block_step");
    public static final ResourceKey<DamageType> BOHRIUM_BLOCK_MINING = createKey("bohrium_block_mining");
    public static final ResourceKey<DamageType> BOHRIUM_BLOCK_KARMA = createKey("bohrium_block_karma");
    public static final ResourceKey<DamageType> HASSIUM_BLOCK_STEP = createKey("hassium_block_step");
    public static final ResourceKey<DamageType> HASSIUM_BLOCK_MINING = createKey("hassium_block_mining");
    public static final ResourceKey<DamageType> HASSIUM_BLOCK_KARMA = createKey("hassium_block_karma");
    public static final ResourceKey<DamageType> MEITNERIUM_BLOCK_STEP = createKey("meitnerium_block_step");
    public static final ResourceKey<DamageType> MEITNERIUM_BLOCK_MINING = createKey("meitnerium_block_mining");
    public static final ResourceKey<DamageType> MEITNERIUM_BLOCK_KARMA = createKey("meitnerium_block_karma");
    public static final ResourceKey<DamageType> DARMSTADTIUM_BLOCK_STEP = createKey("darmstadtium_block_step");
    public static final ResourceKey<DamageType> DARMSTADTIUM_BLOCK_MINING = createKey("darmstadtium_block_mining");
    public static final ResourceKey<DamageType> DARMSTADTIUM_BLOCK_KARMA = createKey("darmstadtium_block_karma");
    public static final ResourceKey<DamageType> ROENTGENIUM_BLOCK_STEP = createKey("roentgenium_block_step");
    public static final ResourceKey<DamageType> ROENTGENIUM_BLOCK_MINING = createKey("roentgenium_block_mining");
    public static final ResourceKey<DamageType> ROENTGENIUM_BLOCK_KARMA = createKey("roentgenium_block_karma");
    public static final ResourceKey<DamageType> COPERNICIUM_BLOCK_STEP = createKey("copernicium_block_step");
    public static final ResourceKey<DamageType> COPERNICIUM_BLOCK_MINING = createKey("copernicium_block_mining");
    public static final ResourceKey<DamageType> COPERNICIUM_BLOCK_KARMA = createKey("copernicium_block_karma");
    public static final ResourceKey<DamageType> NIHONIUM_BLOCK_STEP = createKey("nihonium_block_step");
    public static final ResourceKey<DamageType> NIHONIUM_BLOCK_MINING = createKey("nihonium_block_mining");
    public static final ResourceKey<DamageType> NIHONIUM_BLOCK_KARMA = createKey("nihonium_block_karma");
    public static final ResourceKey<DamageType> FLEROVIUM_BLOCK_STEP = createKey("flerovium_block_step");
    public static final ResourceKey<DamageType> FLEROVIUM_BLOCK_MINING = createKey("flerovium_block_mining");
    public static final ResourceKey<DamageType> FLEROVIUM_BLOCK_KARMA = createKey("flerovium_block_karma");
    public static final ResourceKey<DamageType> MOSCOVIUM_BLOCK_STEP = createKey("moscovium_block_step");
    public static final ResourceKey<DamageType> MOSCOVIUM_BLOCK_MINING = createKey("moscovium_block_mining");
    public static final ResourceKey<DamageType> MOSCOVIUM_BLOCK_KARMA = createKey("mosocvium_block_karma");
    public static final ResourceKey<DamageType> LIVERMORIUM_BLOCK_STEP = createKey("livermorium_block_step");
    public static final ResourceKey<DamageType> LIVERMORIUM_BLOCK_MINING = createKey("livermorium_block_mining");
    public static final ResourceKey<DamageType> LIVERMORIUM_BLOCK_KARMA = createKey("livermorium_block_karma");
    public static final ResourceKey<DamageType> TENNESSINE_BLOCK_STEP = createKey("tennessine_block_step");
    public static final ResourceKey<DamageType> TENNESSINE_BLOCK_MINING = createKey("tennessine_block_mining");
    public static final ResourceKey<DamageType> TENNESSINE_BLOCK_KARMA = createKey("tennessine_block_karma");
    public static final ResourceKey<DamageType> OGANESSON_BLOCK_STEP = createKey("oganesson_block_step");
    public static final ResourceKey<DamageType> OGANESSON_BLOCK_MINING = createKey("oganesson_block_mining");
    public static final ResourceKey<DamageType> OGANESSON_BLOCK_KARMA = createKey("oganesson_block_karma");
    public static final ResourceKey<DamageType> OTHER_RADIATION_STEP = createKey("other_radiation_step");
    public static final ResourceKey<DamageType> OTHER_RADIATION_MINING = createKey("other_radiation_mining");
    public static final ResourceKey<DamageType> OTHER_RADIATION_KARMA = createKey("other_radiation_karma");


    private static ResourceKey<DamageType> createKey(String name) {
        return ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath("jsmenu",  name));
    }

    public static DamageSource getSource(Level level, ResourceKey<DamageType> key, Entity attacker) {
        var registry = level.registryAccess().registryOrThrow(Registries.DAMAGE_TYPE);
        var holder = registry.getHolderOrThrow(key);
        return new DamageSource(holder, attacker);
    }

    public static boolean hurtWithoutKnockback(Player player, DamageSource source, float amount) {
        Vec3 movement = player.getDeltaMovement();
        boolean hurt = player.hurt(source, amount);
        if (hurt) {
            player.setDeltaMovement(movement);
        }
        return hurt;
    }
}
